# plat-caddy Taskfile
#
# Run 'xplat task' to see available commands
# Run 'xplat task <command>' to execute
#
# Uses xplat directory convention:
#   PLAT_BIN  → .bin/   (built binaries)
#   PLAT_DATA → .data/  (runtime data)
#
# Cross-platform: Uses xplat utilities (mkdir, rm, etc.) for Windows compatibility
#
# Pattern: All plat-* taskfiles use TOOLNAME_CMD for full binary path

version: "3"

vars:
  # Binary (with {{exeExt}} for Windows)
  CADDY_BINARY: 'caddy{{exeExt}}'
  CADDY_MAIN: ./cmd/caddy

  # Directories - use PLAT_* from xplat, fallback for standalone task
  CADDY_BIN_DIR: '{{.PLAT_BIN | default ".bin"}}'
  CADDY_DATA_DIR: '{{.PLAT_DATA | default ".data"}}'

  # Full binary path
  CADDY_CMD: '{{.CADDY_BIN_DIR}}/{{.CADDY_BINARY}}'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  check:deps:
    desc: Ensure caddy binary exists
    status:
      - '{{if eq OS "windows"}}if exist "{{.CADDY_CMD}}" (exit 0) else (exit 1){{else}}test -f "{{.CADDY_CMD}}"{{end}}'
    cmds:
      - task: build

  build:
    desc: Build the Caddy binary
    cmds:
      - xplat mkdir -p "{{.CADDY_BIN_DIR}}"
      - go build -o "{{.CADDY_CMD}}" {{.CADDY_MAIN}}

  test:
    desc: Run tests
    cmds:
      - go test ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run || echo "golangci-lint not installed, skipping"

  run:
    desc: Run Caddy with Caddyfile
    deps: [check:deps]
    cmds:
      - '"{{.CADDY_CMD}}" run --config Caddyfile'

  reload:
    desc: Reload Caddy config
    deps: [check:deps]
    cmds:
      - '"{{.CADDY_CMD}}" reload --config Caddyfile'

  validate:
    desc: Validate Caddyfile
    deps: [check:deps]
    cmds:
      - '"{{.CADDY_CMD}}" validate --config Caddyfile'

  fmt:
    desc: Format Caddyfile
    deps: [check:deps]
    cmds:
      - '"{{.CADDY_CMD}}" fmt --overwrite Caddyfile'

  clean:
    desc: Clean build artifacts
    cmds:
      - xplat rm -rf "{{.CADDY_BIN_DIR}}"

  install:
    desc: Install to GOBIN
    cmds:
      - go install {{.CADDY_MAIN}}

  version:
    desc: Show Caddy version
    deps: [check:deps]
    cmds:
      - '"{{.CADDY_CMD}}" version'
